global:
  scrape_interval: 15s # Scrape every 15 seconds

scrape_configs:
  - job_name: 'prometheus'
    # Scrape Prometheus itself
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'model_service'
    # Scrape our FastAPI app 
    static_configs:
      - targets: ['model_service:8000'] 

  - job_name: 'kafka_exporter'
    # Scrape the Kafka exporter 
    static_configs:
      - targets: ['kafka_exporter:9308']
  
  - job_name: 'cadvisor'
    # Scrape cAdvisor for container health metrics 
    static_configs:
      - targets: ['cadvisor:8080']